src/trydjango/urls.py
from django.contrib import admin
from django.urls import include, path
from page.views import homepage_view, about_view
from Timeoff.views import (
    timeoff_create_view, 
    dynamic_lookup_view,
    timeoff_delete_view,
    timeoff_list_view,
)
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', homepage_view),
    path('about/', about_view),
    path('timeoff/', include('Timeoff.urls')),
    # path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',redirect_authenticated_user=True), name='login'),
    path('logout/', user_views.logout_view, name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('<int:myid>/profiledetail/', user_views.profiledetail, name='profiledetail'),
    path('<int:myid>/profileapprove/', user_views.profileapprove, name='profileapprove'),
    path('teacherapply/', user_views.teacherapply, name='teacherapply'),
    path('nonteacherapply/', user_views.nonteacherapply, name='nonteacherapply'),
    path('supervisorapply/', user_views.supervisorapply, name='supervisorapply'),
    path('applyforapply/', user_views.applyforapply, name='applyforapply'),
    path('applyforapply2/', user_views.applyforapply2, name='applyforapply2'),
    path('groupapplylistview', user_views.groupapplylistview, name='groupapplylistview'),
    path('<int:myid>/groupapplychangeview', user_views.groupapplychangeview, name='groupapplychangeview'),
    path('login_success/', user_views.login_success, name='login_success'),    
    path('success/', user_views.success, name='success'),
    path('successgroupapply/', user_views.successgroupapply, name='successgroupapply'),
    
    path('managerlistview/', user_views.managerlistview, name='managerlistview'),
    path('<int:myid>/managerapprove/', user_views.managerapprove, name='managerapprove'),
    path('vplistview/', user_views.vplistview, name='vplistview'),
    path('<int:myid>/vpapprove/', user_views.vpapprove, name='vpapprove'),
    path('secretarylistview/', user_views.secretarylistview, name='secretarylistview'),
    path('<int:myid>/secretaryapprove/', user_views.secretaryapprove, name='secretaryapprove'),
    path('plistview/', user_views.plistview, name='plistview'),
    path('<int:myid>/papprove/', user_views.papprove, name='papprove'),
    path('plistviewdecided/', user_views.plistviewdecided, name='plistviewdecided'),
    path('<int:myid>/papprovedecided/', user_views.papprovedecided, name='papprovedecided'),
    path('userlistview/', user_views.userlistview, name='userlistview'),
    path('<int:myid>/userdetailview/', user_views.userdetailview, name='userdetailview'),
    path('incrementallview/', user_views.incrementallview, name='incrementallview'),
    path('incrementlistview/', user_views.incrementlistview, name='incrementlistview'),
    path('prependinglistview/', user_views.prependinglistview, name='prependinglistview'),
    path('<int:myid>/prependingdetailview/', user_views.prependingdetailview, name='prependingdetailview'),
    path('alllistview/', user_views.alllistview, name='alllistview'),
    path('<int:myid>/alldetailview/', user_views.alldetailview, name='alldetailview'),
    path('documentlistview/', user_views.documentlistview, name='documentlistview'),
    path('<int:myid>/documentdetailview/', user_views.documentdetailview, name='documentdetailview'),
    path('calendarlistview/', user_views.calendarlistview, name='calendarlistview'),
    path('<int:myid>/calendardetailview/', user_views.calendardetailview, name='calendardetailview'),
    path('change_password/', user_views.change_password, name='change_password'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/forms.py
from django import forms
from django.db.models import Q
from django.forms import ModelForm, Textarea, Select
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from customstaff.models import *
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput
from django.core.exceptions import ValidationError
from bootstrap_daterangepicker import widgets, fields
from django.contrib import messages
from datetime import *
# class UserRegisterForm(UserCreationForm):
# 	email = forms.EmailField()

# 	class Meta:
# 		model = User
# 		fields = [
# 			'username',
# 			'email',
# 			'password1',
# 			'password2',
# 		]
TIME_FORMAT = '%I:%M %p'
first = '1st'
second = '2nd'
third = '3rd'
forth = '4th'
fifth = '5th'
sixth = '6th'
seventh = '7th'
eighth = '8th'
ninth = '9th'
class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):

	class Meta:
		model = Profile
		fields = [
			'image',
		]
class ProfileApproveForm(forms.ModelForm):
	# finalcomment = forms.CharField(required=False,label =  "Cancel reason", widget=forms.TextInput(attrs={'placeholder' : "Reason"}) )
	class Meta:
		model = LeaveApplication
		fields = [
			# 'firststatus',
			# 'secondstatus',
			# 'finalstatus'
		]


class TeachingStaffUpdateForm(forms.ModelForm):

	class Meta:
		model = TeachingStaffDetail
		fields = ['sickleave', 'casualleave']

class NonTeachingStaffUpdateForm(forms.ModelForm):

	class Meta:
		model = NonTeachingStaffDetail
		fields = ['sickleave', 'annualleave', 'compensatedleave']

	# def clean(self):
 #    	modify = self.cleaned_data['duration']
 #    	if obj.user.teachertimeofftype == sickleave:
 #    		sickleave = sickleave - modify

	# 	return super(NonTeachingStaffUpdateForm, self).clean()

class TeacherApplyForm(forms.ModelForm):
	
	startdate = forms.DateField(input_formats=('%d/%m/%Y', ),label= 'From Date',widget=DatePickerInput(
		format='%d/%m/%Y',
		options={
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'start-time',
			 'placeholder' : "Pick a Date!",
			 })
			)
						
	starttime = forms.TimeField(required=False, label= 'From Time',widget=TimePickerInput(
		options={"stepping" : 5,
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class' : 'starttime',
			 'placeholder' : "Pick a Time!",
			 })
			)

	enddate = forms.DateField(input_formats=('%d/%m/%Y', ),label= 'To Date',widget=DatePickerInput(
		format='%d/%m/%Y',
		options={
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'start-time',
			 'placeholder' : "Pick a Date!",
			 })
			)
						
	endtime = forms.TimeField(required=False ,label= 'To Time',widget=TimePickerInput(
		options={"stepping" : 5,
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'starttime',
			 'placeholder' : "Pick a Time!",
			 })
			)
	# teachertimeofftype = forms.ChoiceField(required=False, choices = TEACHER_TIMEOFF_CHOICES)

	reason	= forms.CharField(required=True,
		widget=forms.Textarea(
			attrs={
				"cols" : 50,
				"rows" : 3
		}))	
	PERIOD_CHOICES = [
		# ("first" ,'1st'),
		# ("second", '2nd'),
		# ("third" ,'3rd'),
		# ("forth" ,'4th'),
		# ("fifth" ,'5th'),
		# ("sixth" ,'6th'),
		# ("seventh", '7th'),
		# ("eighth", '8th'),
		# ("ninth" ,'9th'),
		# ("allday", 'allday')

		(first ,'1st'),
		(second, '2nd'),
		(third ,'3rd'),
		(forth ,'4th'),
		(fifth ,'5th'),
		(sixth ,'6th'),
		(seventh, '7th'),
		(eighth, '8th'),
		(ninth ,'9th')
	]

	period = forms.MultipleChoiceField(required=False,choices = PERIOD_CHOICES)
	pickvp = forms.ModelChoiceField(required=False,label ="Choose VP",queryset = User.objects.filter(is_viceprincipal = True))

	class Meta:
		model = LeaveApplication
		fields = [
			'teachertimeofftype',
			'pickvp',
			'period',
			'startdate',
			'starttime',
			'enddate',
			'endtime',
			'reason'
			]
		widgets={
			'teachertimeofftype': Select(attrs={"onChange":"showDiv('hidden_div', this)"}),
		}

	# def __init__(self,*args, **kwargs):
	#     super(TeacherApplyForm, self).__init__(*args, **kwargs)
	#     self.fields['teachertimeofftype'].choices =  [('', '---Please select your color---')] + LeaveApplication.TEACHER_TIMEOFF_CHOICES

	def clean(self):
		startdate = self.cleaned_data.get('startdate')
		enddate = self.cleaned_data.get('enddate')
		starttime = self.cleaned_data.get('starttime')
		endtime = self.cleaned_data.get('endtime')
		if starttime != None and endtime != None:
			
			if startdate.day < enddate.day and startdate.month == enddate.month:
				print('111111111')
				
			elif startdate.month < enddate.month:
				print('22222222')
				return endtime
			elif startdate.year < enddate.year:
					return endtime
			elif startdate.month == enddate.month and startdate.day == enddate.day:
				if starttime.minute  >=  endtime.minute and starttime.hour  >=  endtime.hour:
					raise forms.ValidationError(("End date must be later than start date"))
				elif starttime.hour  >  endtime.hour:
					raise forms.ValidationError(("End date must be later than start date"))
			else:
				print('4444444444')
				raise forms.ValidationError(("End date must be later than start date"))
	
		elif starttime == None and endtime == None:
			if startdate.day <= enddate.day and startdate.month == enddate.month:
				print('5555555')
				return endtime
			elif startdate.month < enddate.month:
				print('666666666')
				return endtime
			elif startdate.year < enddate.year:
					return endtime
			else:
				print('7777777')
				raise forms.ValidationError(("End date must be later than start date"))
		else:
			raise forms.ValidationError(("End date must be later than start date"))
class NonTeacherApplyForm(forms.ModelForm):
	
	# date_range_picker = fields.DateRangeField(
	# 	input_formats=['%d/%m/%Y'],
	# 	widget=widgets.DateRangeWidget(
	# 		format='%d/%m/%Y'
	# 		)
	# )

	startdate = forms.DateField(input_formats=('%d/%m/%Y', ),label= 'From Date',widget=DatePickerInput(
		format='%d/%m/%Y',
		options={
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'start-time',
			 'placeholder' : "Pick a Date!",
			 })
			)
						
	starttime = forms.TimeField(required=False, label= 'From Time',widget=TimePickerInput(
		options={"stepping" : 5,
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'starttime',
			 'placeholder' : "Pick a Time!",
			 })
			)

	enddate = forms.DateField(input_formats=('%d/%m/%Y', ),label= 'To Date',widget=DatePickerInput(
		format='%d/%m/%Y',
		options={
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'start-time',
			 'placeholder' : "Pick a Date!",
			 })
			)
						
	endtime = forms.TimeField(required=False, label= 'To Time',widget=TimePickerInput(
		options={"stepping" : 5,
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'starttime',
			 'placeholder' : "Pick a Time!",
			 })
			)
	# nonteachertimeofftype = forms.CharField(required=False)

	
	reason	= forms.CharField(required=True,
		widget=forms.Textarea(
			attrs={
				"cols" : 50,
				"rows" : 3
		}))

	pickvp = forms.ModelChoiceField(required=False,label ="Please Select Vice-Principal",queryset = User.objects.filter(is_viceprincipal = True))
	pickmanager = forms.ModelChoiceField(required=False, label ="Please Select Supervisor(s)",queryset = User.objects.filter(Q(is_supervisor = True) | Q(is_viceprincipal = True)))
	
	PERIOD_CHOICES = [

		(first ,'1st'),
		(second, '2nd'),
		(third ,'3rd'),
		(forth ,'4th'),
		(fifth ,'5th'),
		(sixth ,'6th'),
		(seventh, '7th'),
		(eighth, '8th'),
		(ninth ,'9th')
	]

	period = forms.MultipleChoiceField(required=False,choices = PERIOD_CHOICES) 
	class Meta:
		model = LeaveApplication
		fields = [
			'nonteachertimeofftype',
			'pickvp',
			'pickmanager',
			'startdate',
			'starttime',
			'enddate',
			'endtime',
			'period',
			'reason',
			'file'
		]
		widgets={
				'nonteachertimeofftype': Select(attrs={
					"onChange":"showDiv('hidden_div', this)"
					}),
			}

		
	def clean(self):
		startdate = self.cleaned_data.get('startdate')
		enddate = self.cleaned_data.get('enddate')
		starttime = self.cleaned_data.get('starttime')
		endtime = self.cleaned_data.get('endtime')
		if starttime != None and endtime != None:
			if startdate.day < enddate.day and startdate.month == enddate.month:
				print('111111111')
				# return endtime
			elif startdate.month < enddate.month:
				print('22222222')
				return endtime
			elif startdate.year < enddate.year:
				return endtime
			elif startdate.month == enddate.month and startdate.day == enddate.day:
				if starttime.minute  >=  endtime.minute and starttime.hour  >=  endtime.hour:
					raise forms.ValidationError(("End Time must be later than start Time"))
				elif starttime.hour  >  endtime.hour:
					raise forms.ValidationError(("End Time must be later than start Time"))
			else:
				print('4444444444')
				raise forms.ValidationError(("End date must be later than start date"))
			
		elif starttime == None and endtime == None:
			if startdate.day <= enddate.day and startdate.month == enddate.month:
				print('5555555')
				# return endtime
			elif startdate.month < enddate.month:
				print('666666666')
				# return endtime
			elif startdate.year < enddate.year :
				# return endtime
				print('666666666')
			else:
				print('7777777')
				raise forms.ValidationError(("End date must be later than start date"))
			
		else:
			raise forms.ValidationError(("End date must be later than start date"))
class GroupApplyForm(forms.ModelForm):
	
	startdate = forms.DateField(input_formats=('%d/%m/%Y', ),label= 'From Date',widget=DatePickerInput(
		format='%d/%m/%Y',
		options={
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'start-time',
			 'placeholder' : "Pick a Date!",
			 })
			)
						
	starttime = forms.TimeField(required=False, label= 'From Time',widget=TimePickerInput(
		options={"stepping" : 5,
				"toolbarPlacement" : 'top',
				},

src/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About</h1>
<p>This is about kachi</p>
<p>
	{{ my_text|capfirst|upper}} {{my_num}} {{my_list}}
</p>

{% for my_sub_item in my_list %}
	{% if my_sub_item == 12 %}
		<li>{{ forloop.counter }} is {{ my_sub_item|add:12 }}</li>
	{% endif %}

{% endfor %}

{% endblock %}

src/templates/base.html
<!DOCTYPE HTML>
<html lang="en">

<head>
    <style type="text/css">
    * {
        font-family: 'Noto Sans TC', sans-serif;
    }
   /* p{
        margin-bottom: 80px;
    }
    ul{
        margin-bottom: 80px;
    }*/
    .navbar-nav>li {
        padding-left: 20px;
        padding-right: 20px;
        
    }
    #id_period {
        height: 200px;
    }
    #div_id_period{
        width: 50%;
        height: 100%;
    }

    
    @media not all and (min-resolution:.001dpcm)
    { @supports (-webkit-appearance:none) and (stroke-color:transparent) {
        #div_id_pickuser{
            display: flex;
            flex-direction: column;
        }

        #div_id_period{
            display: flex;
            flex-direction: column;
        }
        #div_id_attachmentrequired{
            display: flex;
            flex-direction: column;
        }
        .check{
            display: flex;
            flex-direction: row;
            
        }
        #id_attachmentrequired{
            display: flex;
            flex-direction: column;
        }
    }}


    .mybar {
      position: fixed;
      width: 100%;
    }

    .fixedbar {
        position: fixed;
        width: 100%;
        top:0;
        overflow: hidden;
        z-index: 3;
    }
    .main{
        margin-top: 150px;
    }

    .media {
        min-height: 5em;
        padding: 1em 4em;
        font: 1em/150% sans-serif;
        position: relative;
        background-color: lightgoldenrodyellow;
    }

    .username {
        position: absolute;
        bottom: 8px;
        right: 16px;
        font-size: 13px;
    }

    .success {
        min-height: 5em;
        padding: 1em 4em;
        font: 1em/150% sans-serif;
        position: relative;
        background-color: lightgoldenrodyellow;
    }

    .logo {
        max-width: 60px;
        margin-right: 20px;
    }

    .h1 {
        text-align: center;
        font-family: Geneva, Arial, Helvetica, Verdana, sans-serif;
        color: blue;
    }

    /*table, th, td {
    border: 1.5px solid black;
  }*/
    .body {
        position:relative;
        display: flex;
        flex-direction: column;
    }

    /*  .table{
    padding: 10px;
  }*/

    .Kachi {
        text-align: center;
        color: white;
        background-color: #99b3b9;
        opacity: 1;
        padding: 10px;
        font-family: Geneva, Arial, Helvetica, Verdana, sans-serif;
        font-size: 35px;
        margin: 0%;
        width: auto;
        position: relative;

    }

    #hidden_div {
        display: none;
    }

    #hidden_div2 {
        display: none;
    }

    p {
        line-height: 12px;
    }

    label,
    input {
        width: 200px;
        float: left;
    }

    .colforapplyandbalance {
        display: flex;
        flex-direction: row;
        justify-content: space-between;

    }

    .colapply {
        display: flex;
        flex-direction: column;
        justify-content: space-around;
    }

    .colbalance {
        display: flex;
        flex-direction: column;
        max-width:
            /*    justify-content: space-around;
*/
    }
    #changepw{
        max-width: 200px;
        display: inline-flex;
        flex-direction: column;
    }
    #checkbox1,
    #checkboxPeriod,
    #checkboxWholeDay {
        width: 30px;
    }

    .startdate {
        text-align: center;
        font-size: 1em;
    }

    .starttime {
        font-size: 1em;
    }

    .content-section-forapply {
        /*margin : 2px 50px 75px 100px;*/
        margin: auto;
        max-width: 100%;
        z-index: 0;
    }

    .content-section {
        margin: auto;
        max-width: 1110px;

    }

    .starttimefield {
        width: 200px;
        margin-right: 10rem;
    }

    .endtimefield {
        width: 200px;
        margin-right: 10rem;
    }

    .row {
        display: flex;
        flex-direction: row;
        justify-content: space-around;
        max-width: 900px;
    }

    .start {
        /*    float : left;
*/
        display: flex;
        flex-direction: row;
        justify-content: left;
    }

    .end {
        display: flex;
        flex-direction: row;
        justify-content: left;
    }

    .endforgroup .check {
        margin-top: 0px;
        float: left;
        padding-left: 30px;
    }

    .hide {
        display: none;
    }

    .reason {
        margin-top: 20px;
        float: bottom;
    }

    .picker {
        margin-top: 45px;
        max-width: 100%;

    }

    .form-group {
        margin-top: 20px;
    }

    hr {
        width: 100%;
        display: block;
        margin-top: 0.5em;
        margin-bottom: 0.5em;
        margin-left: auto;
        margin-right: auto;
        border-style: inset;
        border-width: 1px;
    }

    .profiledetail {
        display: flex;
        flex-direction: column;
        max-width: auto;
        min-height: 5em;
        padding: 1em 4em;
        font: 1em/150% sans-serif;
        position: relative;
        background-color: rgb(252, 252, 232);
    }
/*--------------------------------------------------*/
    $text-background: #99b3b9;
$text-colour:     rgba(255, 255, 255, 1);

[role="progressbar"] {
  position: relative;
  
  p {
    display: block;
    margin: 0;
    height: 60px;
    font-family: Arial,Sacramento, cursive;
    font-size: 1em;
    text-align: center;
    }
  
  &::before,
  &::after {
    display: block;
    height: 120px;
    font-family: Montserrat, Helvetica Neue, Helvetica, Arial, sans-serif;
    font-weight: 700;
    font-size: 6em;
    // text-transform: uppercase;
    content: attr(data-text);
    }
  
  &::before {
    color: $text-colour;
    }
  
  &::after {
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    z-index: 2;
    color: $text-background;
    overflow: hidden;
    }
}

// Busy state
[role="progressbar"][aria-busy="true"]::after {
  animation: load ease-out 10s infinite forwards;
}

@keyframes load {
  0%, 10%, 100% {
    height: 0;
    }
  
  90% {
    height: 120px;
    }
}

// Unimportant bits
@import url(https://fonts.googleapis.com/css?family=Sacramento:400|Montserrat:700);



/*--------------------------------------*/
.loader-wrapper {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  background-color: #242f3f;
  display:flex;
  justify-content: center;
  align-items: center;
}
.loader {
  display: inline-block;
  width: 30px;
  height: 30px;
  position: relative;
  border: 4px solid #Fff;
  animation: loader 2s infinite ease;
}
.loader-inner {
  vertical-align: top;
  display: inline-block;
  width: 100%;
  background-color: #fff;
  animation: loader-inner 2s infinite ease-in;
}
@keyframes loader {
  0% { transform: rotate(0deg);}
  25% { transform: rotate(180deg);}
  50% { transform: rotate(180deg);}
  75% { transform: rotate(360deg);}
  100% { transform: rotate(360deg);}
}
@keyframes loader-inner {
  0% { height: 0%;}
  25% { height: 0%;}
  50% { height: 100%;}
  75% { height: 100%;}
  100% { height: 0%;}
}

    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet" >
    <!-- Bootstrap Dropdown Hover CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href="css/animate.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="css/bootstrap-dropdownhover.min.css" rel="stylesheet">
    
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=full %}
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="scripts/moment-2.4.0.js"></script>
    <script type="text/javascript" src="scripts/bootstrap-datetimepicker.js"></script>
    
    {% block extrahead %}
    {% endblock %}
    <title>Kachi-iLeave</title>
    <meta charset="UTF-8" />
</head>

<body>
    <header>
        {% load static %}
        <div class="fixedbar">
            <div class="Kachi">
                <div style="display: inline-flex;">
                    <a href="http://www.kachi.edu.hk/en"> <img class='logo' src="{% static 'image/kachi.png'%}" alt="PAOC Ka Chi Secondary School"></a>
                    <h2>iLeave System Beta</h2>
                </div>
                <div class="username">{{user.username}}</div>
            </div>
            <div class='mybar'>{% include 'navbar.html' %}</div>
        </div>
    </header>
    <div class="main">
        <table id="menu">
        </table>
        <div class='container'>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <div class='body'>
                {% block content %}
                replace me
                {% endblock %}
            </div>
            <!-- <footer>&copy; 2021 copyrighted</footer>
 -->
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Bootstrap Dropdown Hover JS -->
    <script src="js/bootstrap-dropdownhover.min.js"></script>
</body>

</html>

src/templates/home.html
      {% extends 'base.html' %}

      {% block content %}
      <form action="submit">
       <fieldset>
          <p>
             <label for="startdate">From:</label>
             <input id="startdate" type ="date" placeholder="Enter a date DD/MM/YY">
             <br><br>
             
             <label for="enddate">To:</label>
            <input id="enddate" type ="date" placeholder="Enter a date DD/MM/YY">
             <br><br>
             <label for="myList">Reason:</label>
             <select id = "myList" >
              <option value = "1">Please choose</option>
               <option value = "2">Annual Leave</option>
               <option value = "3">Sick Leave</option>
             </select>
             <button type="submit" value = "Submit">Submit</button>
          </p>
       </fieldset>
    </form>
    {% endblock %}