src/trydjango/urls.py
from django.contrib import admin
from django.urls import include, path
from page.views import homepage_view, about_view
from Timeoff.views import (
    timeoff_create_view, 
    dynamic_lookup_view,
    timeoff_delete_view,
    timeoff_list_view,
)
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', homepage_view),
    path('about/', about_view),
    path('timeoff/', include('Timeoff.urls')),
    # path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',redirect_authenticated_user=True), name='login'),
    path('logout/', user_views.logout_view, name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('<int:myid>/profiledetail/', user_views.profiledetail, name='profiledetail'),
    path('<int:myid>/profileapprove/', user_views.profileapprove, name='profileapprove'),
    path('teacherapply/', user_views.teacherapply, name='teacherapply'),
    path('nonteacherapply/', user_views.nonteacherapply, name='nonteacherapply'),
    path('supervisorapply/', user_views.supervisorapply, name='supervisorapply'),
    path('applyforapply/', user_views.applyforapply, name='applyforapply'),
    path('applyforapply2/', user_views.applyforapply2, name='applyforapply2'),
    path('groupapplylistview', user_views.groupapplylistview, name='groupapplylistview'),
    path('<int:myid>/groupapplychangeview', user_views.groupapplychangeview, name='groupapplychangeview'),
    path('login_success/', user_views.login_success, name='login_success'),    
    path('success/', user_views.success, name='success'),
    path('successgroupapply/', user_views.successgroupapply, name='successgroupapply'),
    
    path('managerlistview/', user_views.managerlistview, name='managerlistview'),
    path('<int:myid>/managerapprove/', user_views.managerapprove, name='managerapprove'),
    path('vplistview/', user_views.vplistview, name='vplistview'),
    path('<int:myid>/vpapprove/', user_views.vpapprove, name='vpapprove'),
    path('secretarylistview/', user_views.secretarylistview, name='secretarylistview'),
    path('<int:myid>/secretaryapprove/', user_views.secretaryapprove, name='secretaryapprove'),
    path('plistview/', user_views.plistview, name='plistview'),
    path('<int:myid>/papprove/', user_views.papprove, name='papprove'),
    path('plistviewdecided/', user_views.plistviewdecided, name='plistviewdecided'),
    path('<int:myid>/papprovedecided/', user_views.papprovedecided, name='papprovedecided'),
    path('userlistview/', user_views.userlistview, name='userlistview'),
    path('<int:myid>/userdetailview/', user_views.userdetailview, name='userdetailview'),
    path('incrementallview/', user_views.incrementallview, name='incrementallview'),
    path('incrementlistview/', user_views.incrementlistview, name='incrementlistview'),
    path('prependinglistview/', user_views.prependinglistview, name='prependinglistview'),
    path('<int:myid>/prependingdetailview/', user_views.prependingdetailview, name='prependingdetailview'),
    path('alllistview/', user_views.alllistview, name='alllistview'),
    path('<int:myid>/alldetailview/', user_views.alldetailview, name='alldetailview'),
    path('documentlistview/', user_views.documentlistview, name='documentlistview'),
    path('<int:myid>/documentdetailview/', user_views.documentdetailview, name='documentdetailview'),
    path('calendarlistview/', user_views.calendarlistview, name='calendarlistview'),
    path('<int:myid>/calendardetailview/', user_views.calendardetailview, name='calendardetailview'),
    path('change_password/', user_views.change_password, name='change_password'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/models.py
from django.db import models
from customstaff.models import User
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from PIL import Image
from django.utils import timezone

# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default='default.jpg', upload_to='profile_pics')

	def __str__(self):
		return f'{self.user.username} Profile'

	def save(self):
		super().save()

		img = Image.open(self.image.path)

		if img.height > 300 or img.width > 300:
			output_size = (300,300)
			img.thumbnail(output_size)
			img.save(self.image.path)

src/users/forms.py
from django import forms
from django.db.models import Q
from django.forms import ModelForm, Textarea, Select
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from customstaff.models import *
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput
from django.core.exceptions import ValidationError
from bootstrap_daterangepicker import widgets, fields
from django.contrib import messages
from datetime import *
# class UserRegisterForm(UserCreationForm):
# 	email = forms.EmailField()

# 	class Meta:
# 		model = User
# 		fields = [
# 			'username',
# 			'email',
# 			'password1',
# 			'password2',
# 		]
TIME_FORMAT = '%I:%M %p'
first = '1st'
second = '2nd'
third = '3rd'
forth = '4th'
fifth = '5th'
sixth = '6th'
seventh = '7th'
eighth = '8th'
ninth = '9th'
class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):

	class Meta:
		model = Profile
		fields = [
			'image',
		]
class ProfileApproveForm(forms.ModelForm):
	# finalcomment = forms.CharField(required=False,label =  "Cancel reason", widget=forms.TextInput(attrs={'placeholder' : "Reason"}) )
	class Meta:
		model = LeaveApplication
		fields = [
			# 'firststatus',
			# 'secondstatus',
			# 'finalstatus'
		]


class TeachingStaffUpdateForm(forms.ModelForm):

	class Meta:
		model = TeachingStaffDetail
		fields = ['sickleave', 'casualleave']

class NonTeachingStaffUpdateForm(forms.ModelForm):

	class Meta:
		model = NonTeachingStaffDetail
		fields = ['sickleave', 'annualleave', 'compensatedleave']

	# def clean(self):
 #    	modify = self.cleaned_data['duration']
 #    	if obj.user.teachertimeofftype == sickleave:
 #    		sickleave = sickleave - modify

	# 	return super(NonTeachingStaffUpdateForm, self).clean()

class TeacherApplyForm(forms.ModelForm):
	
	startdate = forms.DateField(input_formats=('%d/%m/%Y', ),label= 'From Date',widget=DatePickerInput(
		format='%d/%m/%Y',
		options={
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'start-time',
			 'placeholder' : "Pick a Date!",
			 })
			)
						
	starttime = forms.TimeField(required=False, label= 'From Time',widget=TimePickerInput(
		options={"stepping" : 5,
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class' : 'starttime',
			 'placeholder' : "Pick a Time!",
			 })
			)

	enddate = forms.DateField(input_formats=('%d/%m/%Y', ),label= 'To Date',widget=DatePickerInput(
		format='%d/%m/%Y',
		options={
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'start-time',
			 'placeholder' : "Pick a Date!",
			 })
			)
						
	endtime = forms.TimeField(required=False ,label= 'To Time',widget=TimePickerInput(
		options={"stepping" : 5,
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'starttime',
			 'placeholder' : "Pick a Time!",
			 })
			)
	# teachertimeofftype = forms.ChoiceField(required=False, choices = TEACHER_TIMEOFF_CHOICES)

	reason	= forms.CharField(required=True,
		widget=forms.Textarea(
			attrs={
				"cols" : 50,
				"rows" : 3
		}))	
	PERIOD_CHOICES = [
		# ("first" ,'1st'),
		# ("second", '2nd'),
		# ("third" ,'3rd'),
		# ("forth" ,'4th'),
		# ("fifth" ,'5th'),
		# ("sixth" ,'6th'),
		# ("seventh", '7th'),
		# ("eighth", '8th'),
		# ("ninth" ,'9th'),
		# ("allday", 'allday')

		(first ,'1st'),
		(second, '2nd'),
		(third ,'3rd'),
		(forth ,'4th'),
		(fifth ,'5th'),
		(sixth ,'6th'),
		(seventh, '7th'),
		(eighth, '8th'),
		(ninth ,'9th')
	]

	period = forms.MultipleChoiceField(required=False,choices = PERIOD_CHOICES)
	pickvp = forms.ModelChoiceField(required=False,label ="Choose VP",queryset = User.objects.filter(is_viceprincipal = True))

	class Meta:
		model = LeaveApplication
		fields = [
			'teachertimeofftype',
			'pickvp',
			'period',
			'startdate',
			'starttime',
			'enddate',
			'endtime',
			'reason'
			]
		widgets={
			'teachertimeofftype': Select(attrs={"onChange":"showDiv('hidden_div', this)"}),
		}

	# def __init__(self,*args, **kwargs):
	#     super(TeacherApplyForm, self).__init__(*args, **kwargs)
	#     self.fields['teachertimeofftype'].choices =  [('', '---Please select your color---')] + LeaveApplication.TEACHER_TIMEOFF_CHOICES

	def clean(self):
		startdate = self.cleaned_data.get('startdate')
		enddate = self.cleaned_data.get('enddate')
		starttime = self.cleaned_data.get('starttime')
		endtime = self.cleaned_data.get('endtime')
		if starttime != None and endtime != None:
			
			if startdate.day < enddate.day and startdate.month == enddate.month:
				print('111111111')
				
			elif startdate.month < enddate.month:
				print('22222222')
				return endtime
			elif startdate.year < enddate.year:
					return endtime
			elif startdate.month == enddate.month and startdate.day == enddate.day:
				if starttime.minute  >=  endtime.minute and starttime.hour  >=  endtime.hour:
					raise forms.ValidationError(("End date must be later than start date"))
				elif starttime.hour  >  endtime.hour:
					raise forms.ValidationError(("End date must be later than start date"))
			else:
				print('4444444444')
				raise forms.ValidationError(("End date must be later than start date"))
	
		elif starttime == None and endtime == None:
			if startdate.day <= enddate.day and startdate.month == enddate.month:
				print('5555555')
				return endtime
			elif startdate.month < enddate.month:
				print('666666666')
				return endtime
			elif startdate.year < enddate.year:
					return endtime
			else:
				print('7777777')
				raise forms.ValidationError(("End date must be later than start date"))
		else:
			raise forms.ValidationError(("End date must be later than start date"))
class NonTeacherApplyForm(forms.ModelForm):
	
	# date_range_picker = fields.DateRangeField(
	# 	input_formats=['%d/%m/%Y'],
	# 	widget=widgets.DateRangeWidget(
	# 		format='%d/%m/%Y'
	# 		)
	# )

	startdate = forms.DateField(input_formats=('%d/%m/%Y', ),label= 'From Date',widget=DatePickerInput(
		format='%d/%m/%Y',
		options={
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'start-time',
			 'placeholder' : "Pick a Date!",
			 })
			)
						
	starttime = forms.TimeField(required=False, label= 'From Time',widget=TimePickerInput(
		options={"stepping" : 5,
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'starttime',
			 'placeholder' : "Pick a Time!",
			 })
			)

	enddate = forms.DateField(input_formats=('%d/%m/%Y', ),label= 'To Date',widget=DatePickerInput(
		format='%d/%m/%Y',
		options={
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'start-time',
			 'placeholder' : "Pick a Date!",
			 })
			)
						
	endtime = forms.TimeField(required=False, label= 'To Time',widget=TimePickerInput(
		options={"stepping" : 5,
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'starttime',
			 'placeholder' : "Pick a Time!",
			 })
			)
	# nonteachertimeofftype = forms.CharField(required=False)

	
	reason	= forms.CharField(required=True,
		widget=forms.Textarea(
			attrs={
				"cols" : 50,
				"rows" : 3
		}))

	pickvp = forms.ModelChoiceField(required=False,label ="Please Select Vice-Principal",queryset = User.objects.filter(is_viceprincipal = True))
	pickmanager = forms.ModelChoiceField(required=False, label ="Please Select Supervisor(s)",queryset = User.objects.filter(Q(is_supervisor = True) | Q(is_viceprincipal = True)))
	
	PERIOD_CHOICES = [

		(first ,'1st'),
		(second, '2nd'),
		(third ,'3rd'),
		(forth ,'4th'),
		(fifth ,'5th'),
		(sixth ,'6th'),
		(seventh, '7th'),
		(eighth, '8th'),
		(ninth ,'9th')
	]

	period = forms.MultipleChoiceField(required=False,choices = PERIOD_CHOICES) 
	class Meta:
		model = LeaveApplication
		fields = [
			'nonteachertimeofftype',
			'pickvp',
			'pickmanager',
			'startdate',
			'starttime',
			'enddate',
			'endtime',
			'period',
			'reason',
			'file'
		]
		widgets={
				'nonteachertimeofftype': Select(attrs={
					"onChange":"showDiv('hidden_div', this)"
					}),
			}

		
	def clean(self):
		startdate = self.cleaned_data.get('startdate')
		enddate = self.cleaned_data.get('enddate')
		starttime = self.cleaned_data.get('starttime')
		endtime = self.cleaned_data.get('endtime')
		if starttime != None and endtime != None:
			if startdate.day < enddate.day and startdate.month == enddate.month:
				print('111111111')
				# return endtime
			elif startdate.month < enddate.month:
				print('22222222')
				return endtime
			elif startdate.year < enddate.year:
				return endtime
			elif startdate.month == enddate.month and startdate.day == enddate.day:
				if starttime.minute  >=  endtime.minute and starttime.hour  >=  endtime.hour:
					raise forms.ValidationError(("End Time must be later than start Time"))
				elif starttime.hour  >  endtime.hour:
					raise forms.ValidationError(("End Time must be later than start Time"))
			else:
				print('4444444444')
				raise forms.ValidationError(("End date must be later than start date"))
			
		elif starttime == None and endtime == None:
			if startdate.day <= enddate.day and startdate.month == enddate.month:
				print('5555555')
				# return endtime
			elif startdate.month < enddate.month:
				print('666666666')
				# return endtime
			elif startdate.year < enddate.year :
				# return endtime
				print('666666666')
			else:
				print('7777777')
				raise forms.ValidationError(("End date must be later than start date"))
			
		else:
			raise forms.ValidationError(("End date must be later than start date"))
class GroupApplyForm(forms.ModelForm):
	
	startdate = forms.DateField(input_formats=('%d/%m/%Y', ),label= 'From Date',widget=DatePickerInput(
		format='%d/%m/%Y',
		options={
				"toolbarPlacement" : 'top',
				},
		attrs={
			 'class': 'start-time',
			 'placeholder' : "Pick a Date!",
			 })
			)
						
	starttime = forms.TimeField(required=False, label= 'From Time',widget=TimePickerInput(
		options={"stepping" : 5,
				"toolbarPlacement" : 'top',
				},

src/users/templates/users/alldetailview.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}
{% block extrahead %}
{{ form.media }}
{% endblock %}
{% block content %}
<!--  -->

    <div class="content-section">
      <div style = "font-weight: lighter; font-style:italic;"> View Application > <a href="{% url 'alllistview' %}">All Applications </a> > {{ obj.user.username }}'s Application </div> <br>
      <div class="media">
        <div class="media-body">
          <h4 class="account-heading">Applicant : {{ obj.user.username }}</h4>

          <p class="text-secondary">Type of Leave : {{ obj.alltimeofftype }}</p>
          {% if obj.user.is_teacher %}
            {% if obj.teachertimeofftype == 'Casual Leave' %}
              <p class="text-secondary">Casual leave : {{ applicant.casualleave }}</p>
            {% elif obj.teachertimeofftype == 'Sick Leave'%}
              <p class="text-secondary">Sick leave : {{ applicant.sickleave }}</p>
            
            {% endif %}
              
          {% else %}
            {% if obj.nonteachertimeofftype == 'Annual Leave' %}
              <p class="text-secondary">Annual leave : {{ applicant.annualleave }}</p>
            {% elif obj.nonteachertimeofftype == 'Sick Leave'%}
              <p class="text-secondary">Sick leave : {{ applicant.sickleave }}</p>
            {% elif obj.nonteachertimeofftype == 'Over Time'%}
              <p class="text-secondary">Compensated Leave : {{ applicant.compensatedleave }}</p>
            {% endif %}
          {% endif %}
          <p class="text-secondary">Start Date : {{ obj.startdate }}</p>
          <p class="text-secondary">End Date : {{ obj.enddate }}</p>
          {% if obj.finalduration == None %}
            <p class="text-secondary">Duration : {{ obj.duration }}</p>
          {% else %}
            <p class="text-secondary">Duration : {{ obj.finalduration }}</p>
          {% endif %}

          <p class="text-secondary">Applicant Reason : {{ obj.reason }}</p>
          {% if obj.period != "[]" %}
                    <p class="font-weight-bold"> Period : {{ obj.period}}</p>
                    {% endif %}<br>
          <h4 class="account-heading">Supervisor Validation:</h4>          
          <p class="text-secondary">Supervisor Approval Status : {{ obj.firststatus }}</p>
          <p class="text-secondary">Supervisor comment : {{ obj.firstcomment }}</p><br>
          <h4 class="account-heading">Vice Principal Validation:</h4>          
          <p class="text-secondary">Vice Principal Approval Status : {{ obj.secondstatus }}</p>
          <p class="text-secondary">Vice Principal comment : {{ obj.secondcomment }}</p><br>
          <h4 class="account-heading">Principal Validation:</h4>    
          <p class="text-secondary">Principal Approval Status : {{ obj.finalstatus }}</p>
          <p class="text-secondary">Principal comment : {{ obj.finalcomment }}</p><br>
        </div>
      </div>
  
{% if obj.finalstatus == "Pending" %}
     {% if obj.groupapplystatus == False %} 
    <form method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class='form-group'>
            <div style="color: red; font-weight: bold;">{{ form.non_field_errors }}</div>
            <h3 id='leavetitle'>Modify Leave Request</h3>
            <small class='text-muted' id='thankyou'></small>
            <hr>
            <div class='colforapplyandbalance'>
                <div class='colapply'>
                    <!-- <legend class='border-bottom mb-4'> Ka Chi Staff Register </legend> -->
                    {% if user.is_teacher %}
                    <div class="starttimefield">{{ form.teachertimeofftype|as_crispy_field }}</div>
                    {% else %}
                    <div class="starttimefield">{{ form.nonteachertimeofftype|as_crispy_field }}</div>
                    {% endif %}
                    <div class="start">
                        <div class="starttimefield">{{ form.startdate|as_crispy_field }}</div>
                        <div class="starttimefield hide" id='input1'>{{ form.starttime|as_crispy_field }}</div>
                    </div>
                    <div class="end">
                        <div class="endtimefield">{{ form.enddate|as_crispy_field }}</div>
                        <div class="endtimefield hide" id='input2'>{{ form.endtime|as_crispy_field }}</div>
                    </div>
                    <div class="check">
                        <input type="checkbox" id="checkbox1" onclick="changeHideStatus()" />
                        <label for="checkbox1">Time Option</label>
                    </div>
                    {% if user.is_teacher %}
                    {% if user.is_viceprincipal %}
                    {% else %}
                    <div id="hidden_div">{{ form.pickvp|as_crispy_field }}</div>
                    {% endif %}
                    {% else %}
                    <div id="hidden_div">
                        {{ form.pickvp|as_crispy_field }}
                        {{ form.pickmanager|as_crispy_field }}
                    </div>
                    {% endif %}
                </div>
                <div class="period">{{ form.period| as_crispy_field }}</div>
                
            </div>
            <div class="reason">{{ form.reason|as_crispy_field }}</div>
            
        </fieldset>
        <div class='form-group'>
            <button name="modify" type="submit" class="btn btn-primary">Modify</button>
        </div>
    </form>
    {% else %}
    <form method='POST'>
        {% csrf_token %}
        <fieldset class='form-group'>
            <div style="color: red; font-weight: bold;">{{ g_form.non_field_errors }}</div>
            <h3>Modify Group Request</h3>
            <hr />
            <!-- <legend class='border-bottom mb-4'> Ka Chi Staff Register </legend> -->
            <div class='colforapplyandbalance'>
                <div class='colapply'>
                    <div class="start">
                        <div class="starttimefield">{{ g_form.startdate|as_crispy_field }}</div>
                        <div class="starttimefield hide" id='input1'>{{ g_form.starttime|as_crispy_field }}</div>
                    </div>
                    <div class="end">
                        <div class="endtimefield">{{ g_form.enddate|as_crispy_field }}</div>
                        <div class="endtimefield hide" id='input2'>{{ g_form.endtime|as_crispy_field }}</div>
                    </div>
                    <div class="starttimefield">{{ g_form.officialtype|as_crispy_field }}</div>
                    <div class="check">
                        <input type="checkbox" id="checkbox1" onclick="changeHideStatus()" />
                        <label for="checkbox1">Time Option</label>
                    </div><br />
                </div>
                <div class="period">{{ g_form.period| as_crispy_field }}</div>
            </div>
                        
            <div class="picker">{{ g_form.users|as_crispy_field }}</div>
            <div id="displaySelected"></div>
            <textarea name="display" id="display" placeholder="Staff Selected" style="overflow:hidden" readonly></textarea>
                        
            <div style="font-weight: lighter; font-style: italic;"> * Hold control or command to select more than one Staff</div>
            <div class="picker">{{ g_form.reason|as_crispy_field }}</div>
            
        </fieldset>
        <div class='form-group'>
            <button name="modifygroup" type="submit" class="btn btn-primary">Modify</button>
        </div>
    </form>

    {% endif %}
      <hr>
      <form method = 'POST' enctype='multipart/form-data' onsubmit="return confirm('Just want to make sure DID YOU DOUBLE CHECK?');"> 
        {% csrf_token %}
        <fieldset class='form-group'>
          <legend class='border-bottom mb-4'> Cancel Application </legend>
          {{ u_form|crispy }}

        </fieldset>
        <div class='form-group'>
          <button name="cancel" type="submit" class="btn btn-primary" onclick="return confirm('*** WARNING : Check your entry as this is an irreversible action. Do you really want to submit? ***');" >Cancel</button>
        </div>
      </form>
  
    {% elif obj.finalstatus == "Canceled"%}

    {% else %}
      <form> 
        <fieldset class='form-group'>
          <legend class='border-bottom mb-4'> Cancel Application </legend>
          <div style="font-weight: lighter; ">**Canceled by Principal**</div>
        </fieldset>
        <div class='form-group'>
          <button name="cancel" type="submit" class="btn btn-primary" disabled="">Cancel</button>
        </div>
      </form>
    {% endif %}

  <script>
                $(document).ready(function() {
                // $("#checkbox1").prop('checked', false);
                // $("#id_nonteachertimeofftype").prop("selectedIndex","Sick Leave");
                // $("#id_teachertimeofftype").prop("selectedIndex","Sick Leave");
                // $("#id_pickvp").prop("selectedIndex","");
                // $("#id_pickmanager").prop("selectedIndex","");
                $("#id_pickmanager").prop("required",false);
                $("#id_pickvp").prop("required",false);
            });

            let input1;
            let input2;

            function changeHideStatus() {
                if (document.getElementById("checkbox1").checked == true) {

                    document.getElementById("input1").setAttribute("class", "starttimefield");
                    document.getElementById("input2").setAttribute("class", "endtimefield");

                    document.getElementById("id_starttime").value = "";
                    document.getElementById("id_endtime").value = "";
          

                } else {
                    document.getElementById("input1").setAttribute("class", "hide starttimefield");
                    document.getElementById("input2").setAttribute("class", "hide endtimefield");
               

                }
 
            }

            function showDiv(divId, element) {
                document.getElementById(divId).style.display = (element.value == 'Official Leave (Outside)' || element.value == 'Official Leave (In School)' || element.value == 'Over Time') ? 'block' : 'none';

                if (element.value == 'Over Time') {
                    document.getElementById("checkbox1").checked = true;
                    document.getElementById("leavetitle").innerHTML = "Over Time Request"; 
                    document.getElementById("thankyou").innerHTML = "~ Thank you for your contribution :)";
                    console.log("test1");
                    changeHideStatus();
                } else {
                    document.getElementById("checkbox1").checked = false;
                    document.getElementById("leavetitle").innerHTML = "Leave Request";
                    changeHideStatus();
                    console.log("test2");
                }
                

                if (element.value == 'Official Leave (Outside)' || element.value == 'Official Leave (In School)') {
                    document.getElementById("id_pickvp").required = true;
                    console.log(document.getElementById("id_pickvp").required);
                    
                } else {
                    document.getElementById("id_pickvp").value = "";
                    document.getElementById("id_pickvp").required = false;
                    changeHideStatus();
                    console.log("test4");
                }

                if ((element.value == 'Over Time' || element.value == 'Official Leave (Outside)' || element.value == 'Official Leave (In School)')) {
                    document.getElementById("id_pickvp").required = true;
                    document.getElementById("id_pickmanager").required= true;
                    console.log("test5");
                    
                } else {
                    document.getElementById("id_pickvp").value = "";
                    document.getElementById("id_pickmanager").value = "";
                    document.getElementById("id_pickvp").required = false;
                    document.getElementById("id_pickmanager").required= false;
                    changeHideStatus();
                    console.log("test6");
                }
            }
            </script>
 </div>
{% endblock %}

src/users/templates/users/email_groupapply.html
Name of Employee: {{username}}
Type of Leave: {{type}}
Starting Date: {{startdate}}
Ending Date: {{enddate}}
Period: {{period}}
Reason: {{reason}}
Applied By: {{applied_by}}

Your leave application is under process.
 
Remark: All leave applications must be submitted 3 days in advance.

* This is an automated message, please do not reply.

src/users/templates/users/email_staffapply.html
Name of Employee: {{username}}
Type of Leave: {{type}}
Starting Date: {{startdate}}
Ending Date: {{enddate}}
Period: {{period}}
Reason: {{reason}}
 
Your leave application is under process, please remind your supervisor to check and approve the application before the leave day.
 
Before the application process is completed, your application will be checked and approved by your supervisor, vice principal and principal.
 
Remark: All leave applications must be submitted 2 days in advance.

* This is an automated message, please do not reply.

src/users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section" style="width: 300px ; margin-left: auto;margin-right: auto;">

	<form method = 'POST'> 
		{% csrf_token %}
  	<fieldset class='form-group' >
  		<legend class='border-bottom mb-1'> Login </legend>
    	{{ form|crispy }}
    </fieldset>
    <div class='form-group'>
      <button type="submit" class="btn btn-primary">Login</button>
    </div>
	</form>
<div class="border-top pt-3">
	<small class='text-muted'>
	 Recomended Browser for this Website : FireFox, Chrome
	</small>
</div>
  </div>

{% endblock %}

src/users/templates/users/logout.html
{% extends 'base.html' %}
{% block content %}
<h2>Logged out</h2>
	
<div class="border-top pt-3">
	<small class='text-muted'>
		 <a href="{% url 'login' %}">Log in again</a>
	</small>
</div>
  

{% endblock %}